# Preprocessing
The preprocessing relies on the PSML dataset, which provides a dataloader
## The dataloader

In [ ]:
import sys
sys.path.append("/home/lll/thesis_lf_cnn/baselines/benchmark/Code")

from dataloader import TimeSeriesLoader

# just dont reload the kernel loader = TimeSeriesLoader(task = 'forecasting', root = "/media/lll/T9/PSML")

0/67
1/67


100%|██████████| 3/3 [00:15<00:00,  5.07s/it]


2/67


100%|██████████| 3/3 [00:15<00:00,  5.01s/it]


3/67


100%|██████████| 3/3 [00:15<00:00,  5.04s/it]


4/67


100%|██████████| 3/3 [00:15<00:00,  5.07s/it]


5/67


100%|██████████| 3/3 [00:15<00:00,  5.08s/it]


6/67


100%|██████████| 3/3 [00:15<00:00,  5.15s/it]


7/67


100%|██████████| 3/3 [00:15<00:00,  5.09s/it]


8/67


100%|██████████| 3/3 [00:15<00:00,  5.09s/it]


9/67


100%|██████████| 3/3 [00:15<00:00,  5.11s/it]


10/67


100%|██████████| 3/3 [00:15<00:00,  5.10s/it]


11/67


100%|██████████| 3/3 [00:15<00:00,  5.13s/it]


12/67


100%|██████████| 3/3 [00:15<00:00,  5.13s/it]


13/67


100%|██████████| 3/3 [00:15<00:00,  5.13s/it]


14/67


100%|██████████| 3/3 [00:15<00:00,  5.12s/it]


15/67


100%|██████████| 3/3 [00:15<00:00,  5.16s/it]


16/67


100%|██████████| 3/3 [00:15<00:00,  5.18s/it]


17/67


100%|██████████| 3/3 [00:15<00:00,  5.15s/it]


18/67


100%|██████████| 3/3 [00:15<00:00,  5.22s/it]


19/67


100%|██████████| 3/3 [00:15<00:00,  5.10s/it]


20/67


100%|██████████| 3/3 [00:15<00:00,  5.03s/it]


21/67


100%|██████████| 3/3 [00:15<00:00,  5.13s/it]


22/67


100%|██████████| 3/3 [00:15<00:00,  5.11s/it]


23/67


100%|██████████| 3/3 [00:15<00:00,  5.15s/it]


24/67


100%|██████████| 3/3 [00:15<00:00,  5.05s/it]


25/67


100%|██████████| 3/3 [00:15<00:00,  5.10s/it]


26/67


100%|██████████| 3/3 [00:14<00:00,  4.96s/it]


27/67


100%|██████████| 3/3 [00:15<00:00,  5.01s/it]


28/67


100%|██████████| 3/3 [00:15<00:00,  5.05s/it]


29/67


100%|██████████| 3/3 [00:15<00:00,  5.11s/it]


30/67


100%|██████████| 3/3 [00:15<00:00,  5.11s/it]


31/67


100%|██████████| 3/3 [00:15<00:00,  5.08s/it]


32/67


100%|██████████| 3/3 [00:15<00:00,  5.11s/it]


33/67


100%|██████████| 3/3 [00:15<00:00,  5.14s/it]


34/67


100%|██████████| 3/3 [00:15<00:00,  5.13s/it]


35/67


100%|██████████| 3/3 [00:15<00:00,  5.17s/it]


36/67


100%|██████████| 3/3 [00:14<00:00,  4.99s/it]


37/67


100%|██████████| 3/3 [00:15<00:00,  5.17s/it]


38/67


100%|██████████| 3/3 [00:15<00:00,  5.16s/it]


39/67


100%|██████████| 3/3 [00:15<00:00,  5.13s/it]


40/67


100%|██████████| 3/3 [00:15<00:00,  5.14s/it]


41/67


100%|██████████| 3/3 [00:14<00:00,  4.90s/it]


42/67


100%|██████████| 3/3 [00:14<00:00,  4.91s/it]


43/67


100%|██████████| 3/3 [00:15<00:00,  5.10s/it]


44/67


100%|██████████| 3/3 [00:15<00:00,  5.15s/it]


45/67


100%|██████████| 3/3 [00:15<00:00,  5.15s/it]


46/67


100%|██████████| 3/3 [00:15<00:00,  5.13s/it]


47/67


100%|██████████| 3/3 [00:15<00:00,  5.16s/it]


48/67


100%|██████████| 3/3 [00:15<00:00,  5.18s/it]


49/67


100%|██████████| 3/3 [00:15<00:00,  5.19s/it]


50/67


100%|██████████| 3/3 [00:15<00:00,  5.22s/it]


51/67


100%|██████████| 3/3 [00:15<00:00,  5.17s/it]


52/67


100%|██████████| 3/3 [00:15<00:00,  5.12s/it]


53/67


100%|██████████| 3/3 [00:15<00:00,  5.14s/it]


54/67


100%|██████████| 3/3 [00:15<00:00,  5.15s/it]


55/67


100%|██████████| 3/3 [00:15<00:00,  5.14s/it]


56/67


100%|██████████| 3/3 [00:15<00:00,  5.18s/it]


57/67


100%|██████████| 3/3 [00:15<00:00,  5.18s/it]


58/67


100%|██████████| 3/3 [00:15<00:00,  5.17s/it]


59/67


100%|██████████| 3/3 [00:15<00:00,  5.18s/it]


60/67


100%|██████████| 3/3 [00:15<00:00,  5.21s/it]


61/67


100%|██████████| 3/3 [00:15<00:00,  5.16s/it]


62/67


100%|██████████| 3/3 [00:15<00:00,  5.19s/it]


63/67


100%|██████████| 3/3 [00:15<00:00,  5.15s/it]


64/67


100%|██████████| 3/3 [00:15<00:00,  5.11s/it]


65/67


100%|██████████| 3/3 [00:15<00:00,  5.15s/it]


66/67


In [6]:
train_loader, test_loader = loader.load(batch_size=512, shuffle=False) # no shuffle for time series (maybe this is not correct)

In [58]:
print("length of the train data: ", len(train_loader.dataset))
print("length of the test data: ", len(test_loader.dataset))

length of the train data:  3720
length of the test data:  43201


In [62]:
for batch in train_loader:
    print("len(batch):", len(batch))
    for i, item in enumerate(batch):
        print(f"batch[{i}] shape:", item.shape)
    print("if following tensor contains only 0 the mask is not needed: ")
    print(sum(batch[2]==0))
    break


len(batch): 3
batch[0] shape: torch.Size([512, 1331])
batch[1] shape: torch.Size([512, 6])
batch[2] shape: torch.Size([512, 6])
if following tensor contains only 0 the mask is not needed: 
tensor([0, 0, 0, 0, 0, 0])


In [28]:
print("Number of training batches: ", len(train_loader))
print("Number of testing batches: ", len(test_loader))


Number of training batches:  8
Number of testing batches:  85


In [63]:
feature_dim = batch[0].shape[1]

for T in range(1, 200):
    if feature_dim % T == 0:
        print("Fensterlänge:", T, "Features pro Schritt:", feature_dim // T)


batch[0].shape  
print(batch[0][0][:50])    
print(batch[0][0][-50:])    


Fensterlänge: 1 Features pro Schritt: 1331
Fensterlänge: 11 Features pro Schritt: 121
Fensterlänge: 121 Features pro Schritt: 11
tensor([ 7.1042e-01,  9.1583e-03,  0.0000e+00,  0.0000e+00,  0.0000e+00,
         0.0000e+00, -1.0400e+01,  1.2556e+02,  1.5000e+00,  2.2260e+01,
         1.0300e+01,  7.1074e-01,  8.9282e-03,  0.0000e+00,  0.0000e+00,
         0.0000e+00,  0.0000e+00, -1.0400e+01,  1.2535e+02,  1.5000e+00,
         2.2260e+01,  1.0300e+01,  7.1106e-01,  8.6980e-03,  0.0000e+00,
         0.0000e+00,  0.0000e+00,  0.0000e+00, -1.0400e+01,  1.2515e+02,
         1.5000e+00,  2.2260e+01,  1.0300e+01,  7.1138e-01,  8.4678e-03,
         0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00, -1.0400e+01,
         1.2494e+02,  1.5000e+00,  2.2260e+01,  1.0300e+01,  7.1170e-01,
         8.2376e-03,  0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00])
tensor([ 0.0000e+00, -1.1100e+01,  1.0217e+02,  1.5000e+00,  2.2354e+01,
         9.3800e+00,  7.4415e-01,  8.5332e-03,  0.0000e+00,  0.0000

In [41]:
## get column names 
import pandas as pd
cols = pd.read_csv("/media/lll/T9/PSML/processed_dataset/forecasting/CAISO_zone_1_2020.csv", nrows = 0)
print(cols.columns)

Index(['ID', 'month_day', 'weekday', 'holiday', 'DHI', 'DNI', 'GHI',
       'Dew Point', 'Solar Zenith Angle', 'Wind Speed', 'Relative Humidity',
       'Temperature', 'yl_t', 'yl_t+60(val)', 'yl_t+60(flag)',
       'yl_t+1440(val)', 'yl_t+1440(flag)', 'yw_t', 'yw_t+5(val)',
       'yw_t+5(flag)', 'yw_t+30(val)', 'yw_t+30(flag)', 'ys_t', 'ys_t+5(val)',
       'ys_t+5(flag)', 'ys_t+30(val)', 'ys_t+30(flag)', 'train_flag'],
      dtype='object')
