# Processing
The preprocessing relies on the PSML dataset, which provides a dataloader
## The dataloader

In [1]:
import pandas as pd

raw_path = "/media/lll/T9/PSML/Minute-level Load and Renewable/CAISO_zone_1_.csv"
raw = pd.read_csv(raw_path)

print("raw data points (3 years in Caizo zone 1):", len(raw), raw.shape, len(raw)/43201)

raw data points (3 years in Caizo zone 1): 1573923 (1573923, 12) 36.43255943149464


In [2]:
import sys
sys.path.append("/home/lll/thesis_lf_cnn/baselines/benchmark/Code")

from dataloader import TimeSeriesLoader

# just dont reload the kernel 
loader = TimeSeriesLoader(task = 'forecasting', root = "/media/lll/T9/PSML")

0/67
1/67
2/67
3/67
4/67
5/67
6/67
7/67
8/67
9/67
10/67
11/67
12/67
13/67
14/67
15/67
16/67
17/67
18/67
19/67
20/67
21/67
22/67
23/67
24/67
25/67
26/67
27/67
28/67
29/67
30/67
31/67
32/67
33/67
34/67
35/67
36/67
37/67
38/67
39/67
40/67
41/67
42/67
43/67
44/67
45/67
46/67
47/67
48/67
49/67
50/67
51/67
52/67
53/67
54/67
55/67
56/67
57/67
58/67
59/67
60/67
61/67
62/67
63/67
64/67
65/67
66/67


In [3]:
train_loader, test_loader = loader.load(batch_size=512, shuffle=False) # no shuffle for time series (maybe this is not correct)

In [4]:
print("length of the train data: ", len(train_loader.dataset))
print("length of the test data: ", len(test_loader.dataset))

length of the train data:  3720
length of the test data:  43201


In [13]:
print(len(train_loader))

8


In [7]:
for batch in train_loader:
    print("len(batch):", len(batch))
    for i, item in enumerate(batch):
        print(f"batch[{i}] shape:", item.shape)
    print("if following tensor contains only 0 the mask is not needed: ")
    print(sum(batch[2]==0))


len(batch): 3
batch[0] shape: torch.Size([512, 1331])
batch[1] shape: torch.Size([512, 6])
batch[2] shape: torch.Size([512, 6])
if following tensor contains only 0 the mask is not needed: 
tensor([0, 0, 0, 0, 0, 0])
len(batch): 3
batch[0] shape: torch.Size([512, 1331])
batch[1] shape: torch.Size([512, 6])
batch[2] shape: torch.Size([512, 6])
if following tensor contains only 0 the mask is not needed: 
tensor([0, 0, 0, 0, 0, 0])
len(batch): 3
batch[0] shape: torch.Size([512, 1331])
batch[1] shape: torch.Size([512, 6])
batch[2] shape: torch.Size([512, 6])
if following tensor contains only 0 the mask is not needed: 
tensor([0, 0, 0, 0, 0, 0])
len(batch): 3
batch[0] shape: torch.Size([512, 1331])
batch[1] shape: torch.Size([512, 6])
batch[2] shape: torch.Size([512, 6])
if following tensor contains only 0 the mask is not needed: 
tensor([0, 0, 0, 0, 0, 0])
len(batch): 3
batch[0] shape: torch.Size([512, 1331])
batch[1] shape: torch.Size([512, 6])
batch[2] shape: torch.Size([512, 6])
if follo

In [8]:
print("Number of training batches: ", len(train_loader))
print("Number of testing batches: ", len(test_loader))


Number of training batches:  8
Number of testing batches:  85


In [9]:
feature_dim = batch[0].shape[1]

for T in range(1, 200):
    if feature_dim % T == 0:
        print("Fensterlänge:", T, "Features pro Schritt:", feature_dim // T)


batch[0].shape  
print(batch[0][0][:50])    
print(batch[0][0][-50:])    


Fensterlänge: 1 Features pro Schritt: 1331
Fensterlänge: 11 Features pro Schritt: 121
Fensterlänge: 121 Features pro Schritt: 11
tensor([ 1.0785e+00,  1.1828e-01,  6.3931e-01,  6.6000e+01,  9.5500e+02,
         5.8600e+02, -1.2400e+01,  5.6980e+01,  3.6000e+00,  8.4900e+00,
         2.2900e+01,  1.0786e+00,  1.2091e-01,  6.4057e-01,  6.6000e+01,
         9.5560e+02,  5.8780e+02, -1.2400e+01,  5.6888e+01,  3.6000e+00,
         8.4800e+00,  2.2920e+01,  1.0787e+00,  1.2354e-01,  6.4183e-01,
         6.6000e+01,  9.5620e+02,  5.8960e+02, -1.2400e+01,  5.6796e+01,
         3.6000e+00,  8.4700e+00,  2.2940e+01,  1.0788e+00,  1.2617e-01,
         6.4309e-01,  6.6000e+01,  9.5680e+02,  5.9140e+02, -1.2400e+01,
         5.6704e+01,  3.6000e+00,  8.4600e+00,  2.2960e+01,  1.0789e+00,
         1.2880e-01,  6.4435e-01,  6.6000e+01,  9.5740e+02,  5.9320e+02])
tensor([ 6.6360e+02, -1.2800e+01,  5.2616e+01,  3.0000e+00,  7.1320e+00,
         2.5220e+01,  1.0870e+00,  6.1336e-02,  6.9286e-01,  6.9000

In [10]:
## get column names 
import pandas as pd
cols = pd.read_csv("/media/lll/T9/PSML/processed_dataset/forecasting/CAISO_zone_1_2018.csv", nrows = 0)
print(cols.columns)

Index(['ID', 'month_day', 'weekday', 'holiday', 'DHI', 'DNI', 'GHI',
       'Dew Point', 'Solar Zenith Angle', 'Wind Speed', 'Relative Humidity',
       'Temperature', 'yl_t', 'yl_t+60(val)', 'yl_t+60(flag)',
       'yl_t+1440(val)', 'yl_t+1440(flag)', 'yw_t', 'yw_t+5(val)',
       'yw_t+5(flag)', 'yw_t+30(val)', 'yw_t+30(flag)', 'ys_t', 'ys_t+5(val)',
       'ys_t+5(flag)', 'ys_t+30(val)', 'ys_t+30(flag)', 'train_flag'],
      dtype='object')


## Trying to understand where I lose most of my training data

### What does the loading of the processed dataset do?

In [1]:
import pandas as pd
import numpy as np
import sys
sys.path.append("/home/lll/thesis_lf_cnn/baselines/benchmark/Code")

data = pd.read_csv("/media/lll/T9/PSML/processed_dataset/forecasting/CAISO_zone_1_2018.csv")

train_flag = data['train_flag'].to_numpy()
all_train_idx = np.sort(np.argwhere(train_flag == 1).reshape([-1]))
print("training data before sliding window:", len(all_train_idx))

sliding_window = 120
training_index = all_train_idx[sliding_window:]
print("train data after sliding window:", len(training_index))

from BenchmarkModel.LoadForecasting.processing import task_prediction_horizon, external_feature_names

history_column_names = []
target_val_column_names = []
for task_name, task_prediction_horizon_list in task_prediction_horizon.items():
    history_column_names.append(f'y{task_name[0]}_t')
    for horizon_val in task_prediction_horizon_list:
        target_val_column_names.append(f'y{task_name[0]}_t+{horizon_val}(val)')

target_flag_column_names = [c.replace("val", "flag") for c in target_val_column_names]

training_validation_target_flag = data[target_flag_column_names].to_numpy()[training_index[sliding_window:]]
print("training data before flags matrix:", training_validation_target_flag.shape[0])

 # We use all flag filters at the same time which results in losing a big chunk of data
 # Maybe it would be smart to solve the different Horizons one by one and set specialized flag for each one to train each on max data
selected_index = np.argwhere(np.prod(training_validation_target_flag, axis=-1) == 1).reshape([-1])
print("training data after flags matrix (selected_index):", len(selected_index))

only_one_index = np.argwhere(training_validation_target_flag[:, 0] == 1).reshape([-1])
print("training data after first flags filter only (only_one_index):", len(only_one_index))



training data before sliding window: 480960
train data after sliding window: 480840
training data before flags matrix: 480720
training data after flags matrix (selected_index): 3720
training data after first flags filter only (only_one_index): 8011


In [2]:
istory_column_names = []
target_val_column_names = []

for task_name, horizon_list in task_prediction_horizon.items():
    history_column_names.append(f"y{task_name[0]}_t")
    for h in horizon_list:
        target_val_column_names.append(f"y{task_name[0]}_t+{h}(val)")

target_flag_column_names = [c.replace("(val)", "(flag)") for c in target_val_column_names]


training_validation_target_flag = data[target_flag_column_names].to_numpy()[training_index[sliding_window:]]

num_samples = training_validation_target_flag.shape[0]

print("all training data:", num_samples)
print("number of targets:", training_validation_target_flag.shape[1])
print("After every flag filter")

result = []

for i, col in enumerate(target_flag_column_names):
    valid_mask = (training_validation_target_flag[:, i] == 1)
    valid_count = valid_mask.sum()
    result.append((col, valid_count))
    print(f"{col:35s} : {valid_count:6d} / {num_samples}")

# combined filter

all_valid = np.prod(training_validation_target_flag, axis=-1) == 1
print("datapoints left for all filters combined")
print(f"datapoints: {all_valid.sum():6d} / {num_samples}")

all training data: 480720
number of targets: 6
After every flag filter
yl_t+60(flag)                       :   8011 / 480720
yl_t+1440(flag)                     :   7988 / 480720
yw_t+5(flag)                        : 480641 / 480720
yw_t+30(flag)                       : 480604 / 480720
ys_t+5(flag)                        : 234252 / 480720
ys_t+30(flag)                       : 225919 / 480720
datapoints left for all filters combined
datapoints:   3720 / 480720
